name: Release

on:
  push:
    tags:
      - "*"

jobs:
  release-pypi:
    name: release-pypi
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/project/unearth
    permissions:
      id-token: write
      contents: write

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: 18

      - run: npx changelogithub
        continue-on-error: true
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Build artifacts
        run: |
          pipx run build

      - name: Test Build
        run: |
          pip install dist/*.whl
          unearth flask

      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
